var TEXT_HELP1 = "CONNECT ALL THE WIRES FROM THE BATTERY, TO SWITCH ON EVERY LIGHT";
var TEXT_HELP2 = "CLICK ON A PIECE TO ROTATE IT. TRY TO USE LESS SECONDS TO GET MORE POINTS!";

var TEXT_SELECT_LEVEL = "SELECT LEVEL";
var TEXT_SELECT = "SELECT DIFFICULTY";
var TEXT_EASY = "EASY";
var TEXT_MEDIUM = "MEDIUM";
var TEXT_HARD = "HARD";
var TEXT_EXTREME = "EXTREME";

var TEXT_LEVEL = "LEVEL";
var TEXT_PTS = "PTS";
var TEXT_TIME = "TIME";
var TEXT_MULTIPLIER = "DIFFICULTY BONUS: ";
var TEXT_YOUR_BEST_SCORE = "BEST SCORE: ";
var TEXT_TOTAL_SCORE = "TOTAL SCORE: ";
var TEXT_CONGRATS = "CONGRATULATIONS!";
var TEXT_YOU_MADE = "YOU MADE";
var TEXT_GAMEOVER = "SORRY, TIME'S UP!";
var TEXT_END_PANEL = "YOUR FINAL SCORE";
var TEXT_ARE_SURE = "ARE YOU SURE YOU WANT TO EXIT? ALL UNSAVED PROGRESS WILL BE LOST";
var TEXT_CREDITS_DEVELOPED = "DEVELOPED BY";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";
var TEXT_DIFFICULTY = [TEXT_EASY, TEXT_MEDIUM, TEXT_HARD, TEXT_EXTREME];

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";