var CANVAS_WIDTH = 768;
var CANVAS_HEIGHT = 1400;
var CANVAS_WIDTH_HALF = 768 / 2;
var CANVAS_HEIGHT_HALF = 1400 / 2;

var EDGEBOARD_X = 0;
var EDGEBOARD_Y = 200;

var FPS = 30;
var FPS_TIME = 1000 / FPS;
var DISABLE_SOUND_MOBILE = false;

var PRIMARY_FONT = "comfortaa";
var PRIMARY_FONT_COLOUR = "#ffffff";
var SECONDARY_FONT_COLOUR = "#000000";

var STATE_LOADING = 0;
var STATE_MENU = 1;
var STATE_MENU_MODE = 2;
var STATE_LEVEL_SELECT = 3;
var STATE_HELP = 1;
var STATE_GAME = 4;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT = 3;

var MODE_EASY = 0;
var MODE_MEDIUM = 1;
var MODE_HARD = 2;
var MODE_EXTREME = 3;

var NUM_COLS;
var NUM_ROWS;
var TIME;
var SCORE_MULTIPLIER;
var TIMER_REMINDER = 10000; // (IN MS)
var SQUARE_SIZE = 132;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;

var DIRECTION_TOP = 0;
var DIRECTION_RIGHT = 1;
var DIRECTION_BOTTOM = 2;
var DIRECTION_LEFT = 3;

var MATRIX_SCALE = [1, 0.8, 0.6, 0.5];

var SQUARE_T = 0;
var SQUARE_I = 1;
var SQUARE_L = 2;
var SQUARE_CROSS = 3;
var SQUARE_END = 4;
var SQUARE_START = 5;

var NUM_ROWS_PAGE_LEVEL = 3;
var NUM_COLS_PAGE_LEVEL = 4;
var NUM_LEVELS;